### PR TITLE
Add Steam In-Home Broadcast

### PR DESCRIPTION
**Pull request by elnappo**
I added support for Steam In-Home Broadcast.
http://store.steampowered.com/streaming/
https://codingrange.com/blog/steam-in-home-streaming-discovery-protocol

```
255.255.255.255 192.168.1.127 27036 27036 17 1434533166.732 458 0 ffffffff .... 34 00000000 .... 0
```

### CODE REVIEW

**Comment by salcock** [comment]
Is the initial discovery message always 34 bytes in size? If so, that should probably be part of the matching rule.

Also, since this is a broadcast protocol you could also require that there are zero bytes of payload in the opposite direction.

These changes would strengthen the rule a bit and make it less likely that there are false positives (especially given that 0xffffffff is a common payload for many protocols).

**Comment by elnappo** [comment]
Sorry for the late response.

> Is the initial discovery message always 34 bytes in size? If so, that should probably be part of the matching rule.

Discovery is not always 34 bytes.

```
Steam_InHome_Broadcast 255.255.255.255 192.168.1.127 27036 27036 17 1455024540.425 426 0 ffffffff .... 103 00000000 .... 0
Steam_InHome_Broadcast 255.255.255.255 192.168.1.56 27036 27036 17 1455024614.950 436 0 ffffffff .... 102 00000000 .... 0
Steam_InHome_Broadcast 255.255.255.255 192.168.1.56 27036 27036 17 1455025024.231 562 0 ffffffff .... 88 00000000 .... 0
Steam_InHome_Broadcast 192.168.1.127 192.168.1.56 27036 27036 17 1455025073.582 0 312 00000000 .... 0 ffffffff .... 104
Steam_InHome_Broadcast 255.255.255.255 192.168.1.127 27036 27036 17 1455025057.988 471 0 ffffffff .... 33 00000000 .... 0
```

> Also, since this is a broadcast protocol you could also require that there are zero bytes of payload in the opposite direction.

I've added the check for `data->payload_len`

**Comment by elnappo** [comment]
@salcock I'm about to add some ICS protocols e.g. s7comm, modbus. When do you merge your develop branch? Do you have plans to release a new version in the near future? What do you think about adding travis ci and a gitignore file?

I've added travis-ci support in my fork:
- https://github.com/elnappo/libprotoident/blob/travis-ci/.travis.yml
- https://travis-ci.org/elnappo/libprotoident

**Comment by salcock** [comment]
I usually merge develop back into master whenever I do a new release. The
plan is to try and release in the near future, but we've got a handful of
unknown protocols that we'd like to identify first, so probably not for
another month or two.

Shane

**Comment by tpltnt** [comment]
This PR has been lingering for 1.5 years now and shows merge conflicts. Are there any plans to merge this PR in the forseeable future?

**Comment by elnappo** [comment]
I resolved the conflict. Is there anything else which is blocking this pull request?

**Comment by salcock** [comment]
Merged into the develop branch for now (d6a2acebdf0fd2797e406869c7060d26e54d738a), pending further testing for false positives.

**Pull request closed without merging**
